spring:
  application:
    name: movie_review25-49
  datasource:
    url: jdbc:h2:./db/movie_review;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always


  liquibase:
    change-log: classpath:/db/changelog/master.yaml


server:
  port: 8089
